# Generated by Django 4.1.6 on 2024-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
